algoritmo "semnome"
var
   X, Y: inteiro
procedimento soma ( var A, B: inteiro )
inicio
      A <- A + 1
      B <- B + 1
      Escreval( "A soma vale ", A+B)
      Escreval(" Valor de A ", A)
      Escreval(" Valor de B ", B)
fimprocedimento
inicio
      x <- 4
      Y <- 8
      Escreval("Valor de X ", X)
      Escreval( " Valor de Y ", Y)
      soma ( X, Y )
      Escreval( X, Y)
      Escreval("Valor de X ", X)
      Escreval( " Valor de Y ", Y)
fimalgoritmo
